// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: serialize.proto

package aggexec

import (
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_matrixorigin_matrixone_pkg_container_types "github.com/matrixorigin/matrixone/pkg/container/types"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type EncodedBasicInfo struct {
	Id                   int64                                                        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IsDistinct           bool                                                         `protobuf:"varint,2,opt,name=is_distinct,json=isDistinct,proto3" json:"is_distinct,omitempty"`
	NullEmpty            bool                                                         `protobuf:"varint,3,opt,name=null_empty,json=nullEmpty,proto3" json:"null_empty,omitempty"`
	Args                 []github_com_matrixorigin_matrixone_pkg_container_types.Type `protobuf:"bytes,4,rep,name=args,proto3,customtype=github.com/matrixorigin/matrixone/pkg/container/types.Type" json:"args"`
	Ret                  github_com_matrixorigin_matrixone_pkg_container_types.Type   `protobuf:"bytes,5,opt,name=ret,proto3,customtype=github.com/matrixorigin/matrixone/pkg/container/types.Type" json:"ret"`
	XXX_NoUnkeyedLiteral struct{}                                                     `json:"-"`
	XXX_unrecognized     []byte                                                       `json:"-"`
	XXX_sizecache        int32                                                        `json:"-"`
}

func (m *EncodedBasicInfo) Reset()         { *m = EncodedBasicInfo{} }
func (m *EncodedBasicInfo) String() string { return proto.CompactTextString(m) }
func (*EncodedBasicInfo) ProtoMessage()    {}
func (*EncodedBasicInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a7c2bf0e2dbbf4, []int{0}
}
func (m *EncodedBasicInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EncodedBasicInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EncodedBasicInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EncodedBasicInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EncodedBasicInfo.Merge(m, src)
}
func (m *EncodedBasicInfo) XXX_Size() int {
	return m.ProtoSize()
}
func (m *EncodedBasicInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_EncodedBasicInfo.DiscardUnknown(m)
}

var xxx_messageInfo_EncodedBasicInfo proto.InternalMessageInfo

func (m *EncodedBasicInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *EncodedBasicInfo) GetIsDistinct() bool {
	if m != nil {
		return m.IsDistinct
	}
	return false
}

func (m *EncodedBasicInfo) GetNullEmpty() bool {
	if m != nil {
		return m.NullEmpty
	}
	return false
}

type EncodeAggResult struct {
	// basic common result.
	Length   int64    `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
	Capacity int64    `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Results  [][]byte `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
	Empties  [][]byte `protobuf:"bytes,4,rep,name=empties,proto3" json:"empties,omitempty"`
	// fixed result and bytes result.
	RequireInitResult    bool     `protobuf:"varint,5,opt,name=requireInitResult,proto3" json:"requireInitResult,omitempty"`
	RequiredResult       []byte   `protobuf:"bytes,6,opt,name=requiredResult,proto3" json:"requiredResult,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EncodeAggResult) Reset()         { *m = EncodeAggResult{} }
func (m *EncodeAggResult) String() string { return proto.CompactTextString(m) }
func (*EncodeAggResult) ProtoMessage()    {}
func (*EncodeAggResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a7c2bf0e2dbbf4, []int{1}
}
func (m *EncodeAggResult) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EncodeAggResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EncodeAggResult.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EncodeAggResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EncodeAggResult.Merge(m, src)
}
func (m *EncodeAggResult) XXX_Size() int {
	return m.ProtoSize()
}
func (m *EncodeAggResult) XXX_DiscardUnknown() {
	xxx_messageInfo_EncodeAggResult.DiscardUnknown(m)
}

var xxx_messageInfo_EncodeAggResult proto.InternalMessageInfo

func (m *EncodeAggResult) GetLength() int64 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *EncodeAggResult) GetCapacity() int64 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *EncodeAggResult) GetResults() [][]byte {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *EncodeAggResult) GetEmpties() [][]byte {
	if m != nil {
		return m.Empties
	}
	return nil
}

func (m *EncodeAggResult) GetRequireInitResult() bool {
	if m != nil {
		return m.RequireInitResult
	}
	return false
}

func (m *EncodeAggResult) GetRequiredResult() []byte {
	if m != nil {
		return m.RequiredResult
	}
	return nil
}

type EncodedAgg struct {
	Info                 *EncodedBasicInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Result               []byte            `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	Groups               [][]byte          `protobuf:"bytes,3,rep,name=groups,proto3" json:"groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *EncodedAgg) Reset()         { *m = EncodedAgg{} }
func (m *EncodedAgg) String() string { return proto.CompactTextString(m) }
func (*EncodedAgg) ProtoMessage()    {}
func (*EncodedAgg) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a7c2bf0e2dbbf4, []int{2}
}
func (m *EncodedAgg) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EncodedAgg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EncodedAgg.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EncodedAgg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EncodedAgg.Merge(m, src)
}
func (m *EncodedAgg) XXX_Size() int {
	return m.ProtoSize()
}
func (m *EncodedAgg) XXX_DiscardUnknown() {
	xxx_messageInfo_EncodedAgg.DiscardUnknown(m)
}

var xxx_messageInfo_EncodedAgg proto.InternalMessageInfo

func (m *EncodedAgg) GetInfo() *EncodedBasicInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *EncodedAgg) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *EncodedAgg) GetGroups() [][]byte {
	if m != nil {
		return m.Groups
	}
	return nil
}

func init() {
	proto.RegisterType((*EncodedBasicInfo)(nil), "aggexec.EncodedBasicInfo")
	proto.RegisterType((*EncodeAggResult)(nil), "aggexec.EncodeAggResult")
	proto.RegisterType((*EncodedAgg)(nil), "aggexec.EncodedAgg")
}

func init() { proto.RegisterFile("serialize.proto", fileDescriptor_f1a7c2bf0e2dbbf4) }

var fileDescriptor_f1a7c2bf0e2dbbf4 = []byte{
	// 417 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xc1, 0x6e, 0x13, 0x31,
	0x10, 0x86, 0xbb, 0xd9, 0x90, 0x86, 0x69, 0xd5, 0x16, 0x1f, 0xd0, 0x52, 0x89, 0x24, 0xca, 0x01,
	0xe5, 0x40, 0x77, 0x25, 0xb8, 0x71, 0x6b, 0x44, 0x0f, 0xbd, 0x5a, 0x15, 0xd7, 0xca, 0xf1, 0x4e,
	0xdc, 0x51, 0x37, 0xf6, 0x62, 0x7b, 0xa5, 0x86, 0xa7, 0xe0, 0x11, 0x78, 0x9c, 0xde, 0xe0, 0xcc,
	0xa1, 0x42, 0xe1, 0x45, 0x90, 0x1d, 0x07, 0xa1, 0x72, 0xed, 0x6d, 0xbf, 0x7f, 0xec, 0xd9, 0xf9,
	0x7f, 0x0f, 0x1c, 0x3b, 0xb4, 0x24, 0x1a, 0xfa, 0x82, 0x65, 0x6b, 0x8d, 0x37, 0x6c, 0x5f, 0x28,
	0x85, 0x77, 0x28, 0x4f, 0xcf, 0x14, 0xf9, 0x9b, 0x6e, 0x51, 0x4a, 0xb3, 0xaa, 0x94, 0x51, 0xa6,
	0x8a, 0xf5, 0x45, 0xb7, 0x8c, 0x14, 0x21, 0x7e, 0x6d, 0xef, 0x4d, 0xbf, 0xf6, 0xe0, 0xe4, 0x42,
	0x4b, 0x53, 0x63, 0x3d, 0x17, 0x8e, 0xe4, 0xa5, 0x5e, 0x1a, 0x76, 0x04, 0x3d, 0xaa, 0x8b, 0x6c,
	0x92, 0xcd, 0x72, 0xde, 0xa3, 0x9a, 0x8d, 0xe1, 0x80, 0xdc, 0x75, 0x4d, 0xce, 0x93, 0x96, 0xbe,
	0xe8, 0x4d, 0xb2, 0xd9, 0x90, 0x03, 0xb9, 0x8f, 0x49, 0x61, 0xaf, 0x01, 0x74, 0xd7, 0x34, 0xd7,
	0xb8, 0x6a, 0xfd, 0xba, 0xc8, 0x63, 0xfd, 0x79, 0x50, 0x2e, 0x82, 0xc0, 0x3e, 0x41, 0x5f, 0x58,
	0xe5, 0x8a, 0xfe, 0x24, 0x9f, 0x1d, 0xce, 0xe7, 0xf7, 0x0f, 0xe3, 0xbd, 0x9f, 0x0f, 0xe3, 0x0f,
	0xff, 0x4c, 0xba, 0x12, 0xde, 0xd2, 0x9d, 0xb1, 0xa4, 0x48, 0xef, 0x40, 0x63, 0xd5, 0xde, 0xaa,
	0x4a, 0x1a, 0xed, 0x05, 0x69, 0xb4, 0x95, 0x5f, 0xb7, 0xe8, 0xca, 0xab, 0x75, 0x8b, 0x3c, 0xf6,
	0x63, 0x57, 0x90, 0x5b, 0xf4, 0xc5, 0xb3, 0x49, 0xf6, 0x44, 0x6d, 0x43, 0xbb, 0xe9, 0xf7, 0x0c,
	0x8e, 0xb7, 0x91, 0x9c, 0x2b, 0xc5, 0xd1, 0x75, 0x8d, 0x67, 0x2f, 0x61, 0xd0, 0xa0, 0x56, 0xfe,
	0x26, 0xa5, 0x92, 0x88, 0x9d, 0xc2, 0x50, 0x8a, 0x56, 0x48, 0xf2, 0xeb, 0x18, 0x4b, 0xce, 0xff,
	0x32, 0x2b, 0x60, 0xdf, 0xc6, 0xdb, 0xae, 0xc8, 0x83, 0x71, 0xbe, 0xc3, 0x50, 0x09, 0x49, 0x11,
	0xa6, 0x48, 0xf8, 0x0e, 0xd9, 0x5b, 0x78, 0x61, 0xf1, 0x73, 0x47, 0x16, 0x2f, 0x35, 0xf9, 0xed,
	0xcf, 0xa3, 0xbf, 0x21, 0xff, 0xbf, 0xc0, 0xde, 0xc0, 0x51, 0x12, 0xeb, 0x74, 0x74, 0x10, 0xa2,
	0xe0, 0x8f, 0xd4, 0xe9, 0x2d, 0x40, 0x7a, 0xe3, 0x73, 0xa5, 0xd8, 0x19, 0xf4, 0x49, 0x2f, 0x4d,
	0x74, 0x72, 0xf0, 0xee, 0x55, 0x99, 0x36, 0xa7, 0x7c, 0xbc, 0x06, 0x3c, 0x1e, 0x0b, 0xd6, 0xb7,
	0x73, 0x47, 0x83, 0x87, 0x3c, 0x51, 0xd0, 0x95, 0x35, 0x5d, 0xbb, 0x73, 0x97, 0x68, 0x7e, 0x72,
	0xbf, 0x19, 0x65, 0x3f, 0x36, 0xa3, 0xec, 0xd7, 0x66, 0xb4, 0xf7, 0xed, 0xf7, 0x28, 0x5b, 0x0c,
	0xe2, 0xaa, 0xbd, 0xff, 0x13, 0x00, 0x00, 0xff, 0xff, 0x65, 0x3c, 0x6a, 0x9c, 0xb5, 0x02, 0x00,
	0x00,
}

func (m *EncodedBasicInfo) Marshal() (dAtA []byte, err error) {
	size := m.ProtoSize()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EncodedBasicInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.ProtoSize()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EncodedBasicInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	{
		size := m.Ret.ProtoSize()
		i -= size
		if _, err := m.Ret.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintSerialize(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if len(m.Args) > 0 {
		for iNdEx := len(m.Args) - 1; iNdEx >= 0; iNdEx-- {
			{
				size := m.Args[iNdEx].ProtoSize()
				i -= size
				if _, err := m.Args[iNdEx].MarshalTo(dAtA[i:]); err != nil {
					return 0, err
				}
				i = encodeVarintSerialize(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if m.NullEmpty {
		i--
		if m.NullEmpty {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.IsDistinct {
		i--
		if m.IsDistinct {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if m.Id != 0 {
		i = encodeVarintSerialize(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *EncodeAggResult) Marshal() (dAtA []byte, err error) {
	size := m.ProtoSize()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EncodeAggResult) MarshalTo(dAtA []byte) (int, error) {
	size := m.ProtoSize()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EncodeAggResult) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.RequiredResult) > 0 {
		i -= len(m.RequiredResult)
		copy(dAtA[i:], m.RequiredResult)
		i = encodeVarintSerialize(dAtA, i, uint64(len(m.RequiredResult)))
		i--
		dAtA[i] = 0x32
	}
	if m.RequireInitResult {
		i--
		if m.RequireInitResult {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if len(m.Empties) > 0 {
		for iNdEx := len(m.Empties) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Empties[iNdEx])
			copy(dAtA[i:], m.Empties[iNdEx])
			i = encodeVarintSerialize(dAtA, i, uint64(len(m.Empties[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Results) > 0 {
		for iNdEx := len(m.Results) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Results[iNdEx])
			copy(dAtA[i:], m.Results[iNdEx])
			i = encodeVarintSerialize(dAtA, i, uint64(len(m.Results[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.Capacity != 0 {
		i = encodeVarintSerialize(dAtA, i, uint64(m.Capacity))
		i--
		dAtA[i] = 0x10
	}
	if m.Length != 0 {
		i = encodeVarintSerialize(dAtA, i, uint64(m.Length))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *EncodedAgg) Marshal() (dAtA []byte, err error) {
	size := m.ProtoSize()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EncodedAgg) MarshalTo(dAtA []byte) (int, error) {
	size := m.ProtoSize()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EncodedAgg) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Groups) > 0 {
		for iNdEx := len(m.Groups) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Groups[iNdEx])
			copy(dAtA[i:], m.Groups[iNdEx])
			i = encodeVarintSerialize(dAtA, i, uint64(len(m.Groups[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Result) > 0 {
		i -= len(m.Result)
		copy(dAtA[i:], m.Result)
		i = encodeVarintSerialize(dAtA, i, uint64(len(m.Result)))
		i--
		dAtA[i] = 0x12
	}
	if m.Info != nil {
		{
			size, err := m.Info.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSerialize(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintSerialize(dAtA []byte, offset int, v uint64) int {
	offset -= sovSerialize(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EncodedBasicInfo) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovSerialize(uint64(m.Id))
	}
	if m.IsDistinct {
		n += 2
	}
	if m.NullEmpty {
		n += 2
	}
	if len(m.Args) > 0 {
		for _, e := range m.Args {
			l = e.ProtoSize()
			n += 1 + l + sovSerialize(uint64(l))
		}
	}
	l = m.Ret.ProtoSize()
	n += 1 + l + sovSerialize(uint64(l))
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *EncodeAggResult) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Length != 0 {
		n += 1 + sovSerialize(uint64(m.Length))
	}
	if m.Capacity != 0 {
		n += 1 + sovSerialize(uint64(m.Capacity))
	}
	if len(m.Results) > 0 {
		for _, b := range m.Results {
			l = len(b)
			n += 1 + l + sovSerialize(uint64(l))
		}
	}
	if len(m.Empties) > 0 {
		for _, b := range m.Empties {
			l = len(b)
			n += 1 + l + sovSerialize(uint64(l))
		}
	}
	if m.RequireInitResult {
		n += 2
	}
	l = len(m.RequiredResult)
	if l > 0 {
		n += 1 + l + sovSerialize(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *EncodedAgg) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Info != nil {
		l = m.Info.ProtoSize()
		n += 1 + l + sovSerialize(uint64(l))
	}
	l = len(m.Result)
	if l > 0 {
		n += 1 + l + sovSerialize(uint64(l))
	}
	if len(m.Groups) > 0 {
		for _, b := range m.Groups {
			l = len(b)
			n += 1 + l + sovSerialize(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovSerialize(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSerialize(x uint64) (n int) {
	return sovSerialize(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EncodedBasicInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSerialize
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EncodedBasicInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EncodedBasicInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSerialize
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsDistinct", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSerialize
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsDistinct = bool(v != 0)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NullEmpty", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSerialize
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.NullEmpty = bool(v != 0)
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Args", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSerialize
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSerialize
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSerialize
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v github_com_matrixorigin_matrixone_pkg_container_types.Type
			m.Args = append(m.Args, v)
			if err := m.Args[len(m.Args)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ret", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSerialize
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSerialize
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSerialize
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Ret.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSerialize(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSerialize
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EncodeAggResult) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSerialize
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EncodeAggResult: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EncodeAggResult: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Length", wireType)
			}
			m.Length = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSerialize
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Length |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Capacity", wireType)
			}
			m.Capacity = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSerialize
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Capacity |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Results", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSerialize
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSerialize
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSerialize
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Results = append(m.Results, make([]byte, postIndex-iNdEx))
			copy(m.Results[len(m.Results)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Empties", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSerialize
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSerialize
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSerialize
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Empties = append(m.Empties, make([]byte, postIndex-iNdEx))
			copy(m.Empties[len(m.Empties)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequireInitResult", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSerialize
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.RequireInitResult = bool(v != 0)
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequiredResult", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSerialize
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSerialize
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSerialize
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequiredResult = append(m.RequiredResult[:0], dAtA[iNdEx:postIndex]...)
			if m.RequiredResult == nil {
				m.RequiredResult = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSerialize(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSerialize
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EncodedAgg) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSerialize
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EncodedAgg: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EncodedAgg: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Info", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSerialize
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSerialize
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSerialize
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Info == nil {
				m.Info = &EncodedBasicInfo{}
			}
			if err := m.Info.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Result", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSerialize
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSerialize
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSerialize
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Result = append(m.Result[:0], dAtA[iNdEx:postIndex]...)
			if m.Result == nil {
				m.Result = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Groups", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSerialize
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSerialize
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSerialize
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Groups = append(m.Groups, make([]byte, postIndex-iNdEx))
			copy(m.Groups[len(m.Groups)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSerialize(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSerialize
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSerialize(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSerialize
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSerialize
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSerialize
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSerialize
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSerialize
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSerialize
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSerialize        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSerialize          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSerialize = fmt.Errorf("proto: unexpected end of group")
)
